module.exports = Object.freeze({
    FETCH_RECORD: 'FETCH_RECORD',
    FIRST_ORDER: 'FIRST_ORDER',
    LOCK_STATE: 'LOCK_STATE',
    UPDATE_RECORD: 'UPDATE_RECORD',
    UPDATE_RECORD: 'UPDATE_RECORD',
    ROLLBACK: 'ROLLBACK',
    CONFIRM_TRANSACTION: 'CONFIRM_TRANSACTION'
});